apiVersion: v2
kind: application
name: prometheus-operator
version: 0.0.1
dependencies:
  - name: kube-prometheus-stack
    version: 79.7.1
    repository: https://prometheus-community.github.io/helm-charts
